name: hello_spring3

on:
  push:
   branches:
     - master

jobs:
  build:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v1

    - name: Run a maven package
      run: mvn clean package
