name: hello_spring3

on:
  push:
   branches:
     - master

jobs:
  build:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v1

    - name: Run a maven package
      run: mvn clean package

    - name: tomcat deploy

      run: curl -v -u pavan:pavche@01 -T /home/ec2-user/actions-runner/_work/spring3-mvc-maven-xml-hello-world/spring3-mvc-maven-xml-hello-world/target/spring3-mvc-maven-xml-hello-world-1.3.war 'http://ec2-52-66-117-249.ap-south-1.compute.amazonaws.com:8081/manager/hello_spring3'
